[phases.setup]
nixPkgs = [
  "chromium",
  "chromedriver",
  "glib",
  "glibc",
  "libx11",
  "libxcomposite",
  "libxcursor",
  "libxdamage",
  "libxext",
  "libxfixes",
  "libxi",
  "libxrandr",
  "libxrender",
  "libxtst",
  "mesa",
  "nss",
  "freetype",
  "fontconfig",
  "alsa-lib"
]

[start]
cmd = "python main.py"
