[nixpacks]
providers = ["python"]

[phases.setup]
nixPkgs = [
  "chromedriver",
  "chromium",
  "fontconfig",
  "freetype",
  "glib",
  "glibc",
  "alsaLib",
  "mesa",
  "nss",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXrender",
  "xorg.libXtst"
]
