[nixpacks]
providers = ["python"]

[phases.setup]
nixPkgs = [
  "alsa-lib",
  "chromedriver",
  "chromium",
  "fontconfig",
  "freetype",
  "glib",
  "glibc",
  "libX11",
  "libXcomposite",
  "libXcursor",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXi",
  "libXrandr",
  "libXrender",
  "libXtst",
  "mesa",
  "nss"
]
